language: node_js
node_js:
  - lts/dubnium
  - node
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: wZ7j4KJrpo+OgGbBNGuZWVuAoYz6KS1n8sQHxg93Kj8YhyA9HXjwm3OjEfswuc8RBXMIVkZJ3AkXZpIzeJBG4LyPQxghxn1e7ajJd2TIVq9lThFN07coOdzB0IswHBkDoIAOjhh/788jBu1+ioJP3vYaXYKhzdz4/Q+kjgUITPrmECN+RmrzYAr9A+XA0kozRO5Qvq2iieVp2ioGPysjo7H/3K9EQ5I4KYZYajiYh/5mlyEqgBlAbXr63z7qaB7wqVOjinviMxX5GDBWXHukpTEZrZXERWgqkF+XgWswOBMFLnrHAw786kgTT/3hwNInLJ9S12vCoECl4VDPNfX94YtuN48JvZ6bSDDDr3xFAxmcpPltWgE85oFh9NC4DucI44P4u0U/GIrak+Fo3nlHYSpRMHLpIuDkn7Hni0+7QXj48CG2BXDEwhphp6GrvtEvhS+saGmmbDs1bNvpJpzTRr1SXe5fy0+qR1tQaOtblhALmuBF2FHZdQocQLiNU89v7cEFMdVr0kdnilumCWkFzMr81n1Kenv7Mij8lylinJ4eAuS0InfEpKmydcGN4XaycO1Tp+JRJpRqY1Rw2l1wyPcpRjE3F82X1xqf5KCKxoUkfhu3VA8oY7mkjHY2VSmzKsWZeRJ9WtLy+UrFnMq36Wt/uPT0tKgOlAgENXlnfhU=
  file:
    - 'html-link-types.js'
    - 'html-link-types.min.js'
  on:
    tags: true
