language: node_js
node_js:
- lts/boron
- node
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: 2rYZnClvi+0CQgPeVCbhcBnW4KWjIqZXO65iySxo38von1r16J4jnqK0gkWZrSlja5jaSJkEjlxm16T/U0dVYbP7fwOd3r7xq1BwZ6n8CTq4G+LqX122sQXY/30KsVtOUqp4Yv9fpnkiX1La39lT3oURepsJg62Rds4gLfTtsifq5V8seUeVkkFgl9FhcCVBjVXKURjacW+sz21LHu3KJ5HV4qoZ5wrI4ECnI7llZqOzy1oSU/yTqSGRc+yPuzuooJrVVX7rGR1YeRr+5Lus7fMM94TDPYImB+B+lY+QpsdfMLrUjqub1hRTohN/nR77K0XitqIvdpLhD07KtRsvWLX8gk7OttPcVAEjW6AXj3OBcuTKFPOwWDGlSAiq583IoRl5dfeGBz6ghhyculmMuJFmf5MPkQ9bEfb+jFsO3GKV133D3yXKSa5lUGwQfvmQolkcrS1nXPQ/LK/ALPnD2aj5y+4PrR/eEh+5lBjjgwvMCCAOWOcl65UIZgPWN7Hu4g+xhW6xiG3L2tnd18AlxMPSiFqFzlHTSeiiJsAmhJogHFwmg3AAAssTvIH8oHVUNHNG4rpEdR3ZxvJzkifpO85zjUBrc9G+gGSJzbV+OYZdh6XK9c3VgRRAZA2qFQQTUzK73vD+G5PIAZzvbz+1dqIwtzrE/38oJmWI26QLPOQ=
  file:
    - "html-link-types.js"
    - "html-link-types.min.js"
  on:
    tags: true
